services:
  mysql_biblio:
    image: mysql:latest
    container_name: mysql_biblio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: biblioteca_api
      MYSQL_USER: biblio_user
      MYSQL_PASSWORD: biblio_pass
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_biblio_data:/var/lib/mysql
    networks:
      - biblio_net

  api_v1:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_biblio_v1
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql_biblio
    ports:
      - "5001:5005"
    command: uvicorn app.main_v1:app --host 0.0.0.0 --port 5005 --reload
    volumes:
      - ./app:/app/app
    networks:
      - biblio_net

  api_v2:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_biblio_v2
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql_biblio
    ports:
      - "5002:5005"
    command: uvicorn app.main_v2:app --host 0.0.0.0 --port 5005 --reload
    volumes:
      - ./app:/app/app
    networks:
      - biblio_net

  api_v3:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_biblio_v3
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql_biblio
    ports:
      - "5003:5005"
    command: uvicorn app.main_v3:app --host 0.0.0.0 --port 5005 --reload
    volumes:
      - ./app:/app/app
    networks:
      - biblio_net

  api_v4:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_biblio_v4
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql_biblio
    ports:
      - "5004:5005"
    command: uvicorn app.main_v4:app --host 0.0.0.0 --port 5005 --reload
    volumes:
      - ./app:/app/app
    networks:
      - biblio_net

  api_v5:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_biblio_v5
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql_biblio
    ports:
      - "5005:5005"
    command: uvicorn app.main_v5:app --host 0.0.0.0 --port 5005 --reload
    volumes:
      - ./app:/app/app
    networks:
      - biblio_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_biblio
    restart: always
    env_file:
      - .env
    depends_on:
      - api_v1
      - api_v2
      - api_v3
      - api_v4
      - api_v5
    ports:
      - "9001:9000"
    volumes:
      - ./frontend:/app
    networks:
      - biblio_net

volumes:
  mysql_biblio_data:

networks:
  biblio_net:
